# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Xxx(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, xxx: str=None):  # noqa: E501
        """Xxx - a model defined in Swagger

        :param id: The id of this Xxx.  # noqa: E501
        :type id: int
        :param xxx: The xxx of this Xxx.  # noqa: E501
        :type xxx: str
        """
        self.swagger_types = {
            'id': int,
            'xxx': str
        }

        self.attribute_map = {
            'id': 'id',
            'xxx': 'xxx'
        }
        self._id = id
        self._xxx = xxx

    @classmethod
    def from_dict(cls, dikt) -> 'Xxx':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Xxx of this Xxx.  # noqa: E501
        :rtype: Xxx
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Xxx.


        :return: The id of this Xxx.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Xxx.


        :param id: The id of this Xxx.
        :type id: int
        """

        self._id = id

    @property
    def xxx(self) -> str:
        """Gets the xxx of this Xxx.


        :return: The xxx of this Xxx.
        :rtype: str
        """
        return self._xxx

    @xxx.setter
    def xxx(self, xxx: str):
        """Sets the xxx of this Xxx.


        :param xxx: The xxx of this Xxx.
        :type xxx: str
        """

        self._xxx = xxx
